language: python
sudo: false
os:
  - linux
python:
  - 3.6
  - 3.6-dev
  - 3.7-dev
  - nightly
before_install:
  - pip install numpy
  - pip install scipy
  - pip install scikit-learn
  - pip install numba
  - pip install hypothesis
  - pip install pytest 
  - pip install pytest-cov
  - pip install codecov
  - pip install sphinx
  - pip install sphinx_rtd_theme
script:
  - pytest
  - sphinx-build docs docs/_build
after_success:
  - codecov
